use MEG;
INSERT INTO Secao VALUES(1, 'Agricultura, pecuária, produção florestal, pesca e aquicultura');
INSERT INTO Secao VALUES(2, 'Indústrias extrativas');
INSERT INTO Secao VALUES(3, 'Indústrias de transformação');
INSERT INTO Secao VALUES(4, 'Eletricidade e gás');
INSERT INTO Secao VALUES(5, 'Água, esgoto, atividades de gestão de resíduos e descontaminação');
INSERT INTO Secao VALUES(6, 'Construção');
INSERT INTO Secao VALUES(7, 'Comércio, reparação de veículos automotores e motocicletas');
INSERT INTO Secao VALUES(8, 'Transporte, armazenagem e correio');
INSERT INTO Secao VALUES(9, 'Alojamento e alimentação');
INSERT INTO Secao VALUES(10, 'Informação e comunicação');
INSERT INTO Secao VALUES(11, 'Atividades financeiras, de seguros e serviços relacionados');
INSERT INTO Secao VALUES(12, 'Atividades imobiliárias');
INSERT INTO Secao VALUES(13, 'Atividades profissionais, científicas e técnicas');
INSERT INTO Secao VALUES(14, 'Atividades administrativas e serviços complementares');
INSERT INTO Secao VALUES(15, 'Administração pública, defesa e seguridade social');
INSERT INTO Secao VALUES(16, 'Educação');
INSERT INTO Secao VALUES(17, 'Saúde humana e serviços sociais');
INSERT INTO Secao VALUES(18, 'Artes, cultura, esporte e recreação');
INSERT INTO Secao VALUES(19, 'Outras atividades de serviços');
INSERT INTO Secao VALUES(20, 'Serviços domésticos');
INSERT INTO Secao VALUES(21, 'Organismos internacionais e outras instituições extraterritoriais');